package:
  name: music21
  version: "2.2.1"

source:
  fn: music21-2.2.1.tar.gz
  url: https://github.com/cuthbertLab/music21/releases/download/v.2.2.1/music21-2.2.1.tar.gz
  md5: db1ca42b8e7fda2e540b7cdbc11bf06a

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - matplotlib

test:
  imports:
    - music21

  requires:
    - python ==3.5

  commands:
    #- python ${SRC_DIR}/music21/test/multiprocessTest.py

about:
  home: https://github.com/cuthbertLab/music21
  license: GNU Lesser General Public License v3 or later (LGPLv3+), or BSD 3-Clause License
  license_file: music21/license.txt
  summary: 'A Toolkit for Computer-Aided Musical Analysis and Manipulation.'
