package:
  name: music21
  version: "3.0.3alpha"

source:
  fn: music21-3.0.3.tar.gz
  url: https://github.com/cuthbertLab/music21/releases/download/v3.0.3-alpha/music21-3.0.3.tar.gz
  md5: 8aeac77690505db2d9a41a8ab745a5f0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - matplotlib

test:
  imports:
    - music21

  requires:
    - python ==3.4

  commands:
    #- python ${SRC_DIR}/music21/test/multiprocessTest.py

about:
  home: https://github.com/cuthbertLab/music21
  license: GNU Lesser General Public License v3 or later (LGPLv3+), or BSD 3-Clause License
  license_file: music21/license.txt
  summary: 'A Toolkit for Computer-Aided Musical Analysis and Manipulation.'
