package:
  name: tmux
  version: "2.4"

source:
  url: https://github.com/tmux/tmux/releases/download/2.4/tmux-2.4.tar.gz
  sha256: 757d6b13231d0d9dd48404968fc114ac09e005d475705ad0cd4b7166f799b349

requirements:
  build:
    - libevent

about:
  home: https://tmux.github.io/
  license: BSD
  summary: "Terminal multiplexer"
