package:
  name: tree
  version: "1.7.0"

source:
  url: http://mama.indstate.edu/users/ice/tree/src/tree-1.7.0.tgz
  sha256: 6957c20e82561ac4231638996e74f4cfa4e6faabc5a2f511f0b4e3940e8f7b12
  patches:
    - fix-prefix.patch

about:
  home: http://mama.indstate.edu/users/ice/tree/
  license: GPL v2
  summary: "Tree is a recursive directory listing program that produces a depth indented listing of files."
